### PR TITLE
Component CLI

### PR DESCRIPTION
**Pull request by damnhipster**
```bash
component new button
```

I haven't found a way to invoke gulp tasks yet, but I'm sure it's possible. Until then, the CLI doesn't do much.

### CODE REVIEW

**Comment by peter-mouland** [comment]
brilliant, i like it :)

**Comment by peter-mouland** [comment]
looking at the code though, the `git clone` step seems to have been removed. This means we either have to assume they have added it to git hub and ask them for the git address (or maybe just the user-name) or tell them to do the following : 
```
git remote add git@github.com:username/component-name
```

Automatic would obviously be better, you able to incorporate this before i accept the pull request?

**Comment by damnhipster** [comment]
Hmm, maybe it would be better to let the user add the correct git remote themselves... The CLI can initialise an empty git repo so the gulp tasks work, and then the user can choose what the remote should be.

The gulp tasks around GH pages require a remote to push to, so it'll need to be compulsory.

**Comment by damnhipster** [comment]
Is the following automatic enough? :wink: 

```bash
npm install -g gulp-component-helper
component new #follow prompts
cd new-component
gulp serve
```

**Comment by peter-mouland** [comment]
ha ha - yup, that'll do nicely!

**Pull request merged**
